baseURL = "https://antonyderham.me"
languageCode = "en-gb"
title = "Antony Derham"
theme = "minimal"
disqusShortname = "ant59" # delete this to disable disqus comments
googleAnalytics = "UA-111367451-1"

[params]
    author = "Antony Derham"
    description = "Personal Blog"
    githubUsername = "ant59"
    accent = "#9C27B0"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:antony@derham.me"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/ant59/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/antonyderham/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/antonyderham/"
    name = "linkedin"
    weight = 4
